# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: ChatController
# Author: https://www.mc-market.org/members/89497/
# Description: Plugin to handle in-game chat.
# Dependencies:
#   -> MySQL Database
#   -> PLJRApi
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  bungee: false #-> Should we use bungee functions?
  bungee-admin-chat: false #-> Should admin-chat be bungee?
  admin-chat: "#" #-> What should we look for, when trying to send AdminChat message?
  sounds: true #-> Should we use sounds?
  broadcast: 600 #-> How often should broadcasts happen?
  join-message: true #-> Should we send player message on join?
  join-title: true #-> Should we show player title on join?
  join-actionbar: true #-> Should we show player actionbar on join?
  mention-message: true #-> Should we send player message, when mentioned?
  mention-title: true #-> Should we send player title, when mentioned?
  mention-actionbar: true #-> Should we send player actionbar, when mentioned?
  cache-players: true # Should we save player data in memory? (false = loading on each join)
#|--------------------------------------------------------------------------------------------------------------------|#

################\
# Groups Setup ############################################################\
################ Here, you can edit and create formats of chat per group. # \
               ############################################################  \

# Used to save space in the groups setup, the message set here,
# will be replaced in groups, using {player} as placeholders.
player: "<hover:show_text:'Click to send private message.'><click:suggest_command:'/msg %player_name%'>&f%player_name%</click></hover>"

groups:
  # Permission to use: "chatcontroller.groups.<group>"
  admin: "&cAdmin {player} &8> &7<pre>{message}</pre>"
  default: "{player} &8> &7<pre>{message}</pre>"
#|--------------------------------------------------------------------------------------------------------------------|#

####################\
# Broadcasts Setup ####################################################\
#################### Here, you can edit and create custom broadcasts. # \
                   ####################################################  \
broadcasts:
  1:
    perm: ""
    sound: "CLICK"
    message:
      enabled: true
      text:
        - ""
        - "&aBroadcast"
        - "This broadcast can see everyone!"
        - ""
    title:
      enabled: true
      title:
        title: "&aBroadcast"
        subtitle: "Everyone can see this!"
        in: 10
        stay: 40
        out: 10
    actionbar:
      enabled: true
      actionbar:
        message: "&aBroadcast: &fEveryone can see this!"
        duration: 40
  two:
    perm: "chatcontroller.broadcast.admin"
    sound: "CLICK"
    message:
      enabled: true
      text:
        - ""
        - "&cBroadcast"
        - "You have permission to see this!"
        - ""
    title:
      enabled: true
      title:
        title: "&cBroadcast"
        subtitle: "You have permission to see this!"
        in: 10
        stay: 40
        out: 10
    actionbar:
      enabled: true
      actionbar:
        message: "&cBroadcast: &fYou have permission to see this!"
        duration: 40
#|--------------------------------------------------------------------------------------------------------------------|#

########################\
# Death Messages Setup ########################################################\
######################## Here, you can edit and create custom death messages. # \
                       ########################################################  \
death-messages:
  player:
    - "&4☠ &c{attacker} &7killed &c{victim}&7!"
    - "&4☠ &c{victim} &7got killed by &c{victim}&7!"
  causes:
    1:
      type: "FALL"
      messages:
        - "&4☠ &c{victim} &7broke his legs by falling."
        - "&4☠ &c{victim} &7slipped."
#|--------------------------------------------------------------------------------------------------------------------|#