package me.pljr.chatcontroller.enums;

public enum Lang {
    NO_CONSOLE,
    ADMIN_CHAT_FORMAT,
    MSG_FAILURE_IGNORING,
    MSG_FAILURE_BLOCKED,
    MSGIGNORE_SUCCESS_FULLIGNORE_ON,
    MSGIGNORE_SUCCESS_FULLIGNORE_OFF,
    MSGIGNORE_SUCCESS_IGNORE,
    MSGIGNORE_SUCCESS_UNIGNORE,
    ACHATCONTROLLER_SPY_ON,
    ACHATCONTROLLER_SPY_OFF,
    ADMIN_SPY,
    MESSAGE_JOIN_FIRST,
    MESSAGE_JOIN,
    MESSAGE_LEAVE
}
